//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type BookmarkField struct {
	ID         uuid.UUID `sql:"primary_key"`
	BookmarkID uuid.UUID
	Index      int32
	Name       string
	Hidden     bool
	CreatedAt  time.Time
	DeletedAt  *time.Time
}
