// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.2
// source: aufheben/v1/aufheben.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Laboof_TagCreate_FullMethodName      = "/aufheben.v1.Laboof/TagCreate"
	Laboof_TagList_FullMethodName        = "/aufheben.v1.Laboof/TagList"
	Laboof_TagGet_FullMethodName         = "/aufheben.v1.Laboof/TagGet"
	Laboof_TagUpdate_FullMethodName      = "/aufheben.v1.Laboof/TagUpdate"
	Laboof_TagDelete_FullMethodName      = "/aufheben.v1.Laboof/TagDelete"
	Laboof_TagPurge_FullMethodName       = "/aufheben.v1.Laboof/TagPurge"
	Laboof_DomainCreate_FullMethodName   = "/aufheben.v1.Laboof/DomainCreate"
	Laboof_DomainList_FullMethodName     = "/aufheben.v1.Laboof/DomainList"
	Laboof_DomainGet_FullMethodName      = "/aufheben.v1.Laboof/DomainGet"
	Laboof_DomainUpdate_FullMethodName   = "/aufheben.v1.Laboof/DomainUpdate"
	Laboof_DomainDelete_FullMethodName   = "/aufheben.v1.Laboof/DomainDelete"
	Laboof_DomainPurge_FullMethodName    = "/aufheben.v1.Laboof/DomainPurge"
	Laboof_BookmarkCreate_FullMethodName = "/aufheben.v1.Laboof/BookmarkCreate"
	Laboof_BookmarkList_FullMethodName   = "/aufheben.v1.Laboof/BookmarkList"
	Laboof_BookmarkGet_FullMethodName    = "/aufheben.v1.Laboof/BookmarkGet"
	Laboof_BookmarkUpdate_FullMethodName = "/aufheben.v1.Laboof/BookmarkUpdate"
	Laboof_BookmarkDelete_FullMethodName = "/aufheben.v1.Laboof/BookmarkDelete"
	Laboof_BookmarkPurge_FullMethodName  = "/aufheben.v1.Laboof/BookmarkPurge"
)

// LaboofClient is the client API for Laboof service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LaboofClient interface {
	TagCreate(ctx context.Context, in *TagCreateRequest, opts ...grpc.CallOption) (*TagCreateResponse, error)
	TagList(ctx context.Context, in *TagListRequest, opts ...grpc.CallOption) (*TagListResponse, error)
	TagGet(ctx context.Context, in *TagGetRequest, opts ...grpc.CallOption) (*TagGetResponse, error)
	TagUpdate(ctx context.Context, in *TagUpdateRequest, opts ...grpc.CallOption) (*TagUpdateResponse, error)
	TagDelete(ctx context.Context, in *TagDeleteRequest, opts ...grpc.CallOption) (*TagDeleteResponse, error)
	TagPurge(ctx context.Context, in *TagPurgeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DomainCreate(ctx context.Context, in *DomainCreateRequest, opts ...grpc.CallOption) (*DomainCreateResponse, error)
	DomainList(ctx context.Context, in *DomainListRequest, opts ...grpc.CallOption) (*DomainListResponse, error)
	DomainGet(ctx context.Context, in *DomainGetRequest, opts ...grpc.CallOption) (*DomainGetResponse, error)
	DomainUpdate(ctx context.Context, in *DomainUpdateRequest, opts ...grpc.CallOption) (*DomainUpdateResponse, error)
	DomainDelete(ctx context.Context, in *DomainDeleteRequest, opts ...grpc.CallOption) (*DomainDeleteResponse, error)
	DomainPurge(ctx context.Context, in *DomainPurgeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	BookmarkCreate(ctx context.Context, in *BookmarkCreateRequest, opts ...grpc.CallOption) (*BookmarkCreateResponse, error)
	BookmarkList(ctx context.Context, in *BookmarkListRequest, opts ...grpc.CallOption) (*BookmarkListResponse, error)
	BookmarkGet(ctx context.Context, in *BookmarkGetRequest, opts ...grpc.CallOption) (*BookmarkGetResponse, error)
	BookmarkUpdate(ctx context.Context, in *BookmarkUpdateRequest, opts ...grpc.CallOption) (*BookmarkUpdateResponse, error)
	BookmarkDelete(ctx context.Context, in *BookmarkDeleteRequest, opts ...grpc.CallOption) (*BookmarkDeleteResponse, error)
	BookmarkPurge(ctx context.Context, in *BookmarkPurgeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type laboofClient struct {
	cc grpc.ClientConnInterface
}

func NewLaboofClient(cc grpc.ClientConnInterface) LaboofClient {
	return &laboofClient{cc}
}

func (c *laboofClient) TagCreate(ctx context.Context, in *TagCreateRequest, opts ...grpc.CallOption) (*TagCreateResponse, error) {
	out := new(TagCreateResponse)
	err := c.cc.Invoke(ctx, Laboof_TagCreate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *laboofClient) TagList(ctx context.Context, in *TagListRequest, opts ...grpc.CallOption) (*TagListResponse, error) {
	out := new(TagListResponse)
	err := c.cc.Invoke(ctx, Laboof_TagList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *laboofClient) TagGet(ctx context.Context, in *TagGetRequest, opts ...grpc.CallOption) (*TagGetResponse, error) {
	out := new(TagGetResponse)
	err := c.cc.Invoke(ctx, Laboof_TagGet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *laboofClient) TagUpdate(ctx context.Context, in *TagUpdateRequest, opts ...grpc.CallOption) (*TagUpdateResponse, error) {
	out := new(TagUpdateResponse)
	err := c.cc.Invoke(ctx, Laboof_TagUpdate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *laboofClient) TagDelete(ctx context.Context, in *TagDeleteRequest, opts ...grpc.CallOption) (*TagDeleteResponse, error) {
	out := new(TagDeleteResponse)
	err := c.cc.Invoke(ctx, Laboof_TagDelete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *laboofClient) TagPurge(ctx context.Context, in *TagPurgeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Laboof_TagPurge_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *laboofClient) DomainCreate(ctx context.Context, in *DomainCreateRequest, opts ...grpc.CallOption) (*DomainCreateResponse, error) {
	out := new(DomainCreateResponse)
	err := c.cc.Invoke(ctx, Laboof_DomainCreate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *laboofClient) DomainList(ctx context.Context, in *DomainListRequest, opts ...grpc.CallOption) (*DomainListResponse, error) {
	out := new(DomainListResponse)
	err := c.cc.Invoke(ctx, Laboof_DomainList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *laboofClient) DomainGet(ctx context.Context, in *DomainGetRequest, opts ...grpc.CallOption) (*DomainGetResponse, error) {
	out := new(DomainGetResponse)
	err := c.cc.Invoke(ctx, Laboof_DomainGet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *laboofClient) DomainUpdate(ctx context.Context, in *DomainUpdateRequest, opts ...grpc.CallOption) (*DomainUpdateResponse, error) {
	out := new(DomainUpdateResponse)
	err := c.cc.Invoke(ctx, Laboof_DomainUpdate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *laboofClient) DomainDelete(ctx context.Context, in *DomainDeleteRequest, opts ...grpc.CallOption) (*DomainDeleteResponse, error) {
	out := new(DomainDeleteResponse)
	err := c.cc.Invoke(ctx, Laboof_DomainDelete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *laboofClient) DomainPurge(ctx context.Context, in *DomainPurgeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Laboof_DomainPurge_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *laboofClient) BookmarkCreate(ctx context.Context, in *BookmarkCreateRequest, opts ...grpc.CallOption) (*BookmarkCreateResponse, error) {
	out := new(BookmarkCreateResponse)
	err := c.cc.Invoke(ctx, Laboof_BookmarkCreate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *laboofClient) BookmarkList(ctx context.Context, in *BookmarkListRequest, opts ...grpc.CallOption) (*BookmarkListResponse, error) {
	out := new(BookmarkListResponse)
	err := c.cc.Invoke(ctx, Laboof_BookmarkList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *laboofClient) BookmarkGet(ctx context.Context, in *BookmarkGetRequest, opts ...grpc.CallOption) (*BookmarkGetResponse, error) {
	out := new(BookmarkGetResponse)
	err := c.cc.Invoke(ctx, Laboof_BookmarkGet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *laboofClient) BookmarkUpdate(ctx context.Context, in *BookmarkUpdateRequest, opts ...grpc.CallOption) (*BookmarkUpdateResponse, error) {
	out := new(BookmarkUpdateResponse)
	err := c.cc.Invoke(ctx, Laboof_BookmarkUpdate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *laboofClient) BookmarkDelete(ctx context.Context, in *BookmarkDeleteRequest, opts ...grpc.CallOption) (*BookmarkDeleteResponse, error) {
	out := new(BookmarkDeleteResponse)
	err := c.cc.Invoke(ctx, Laboof_BookmarkDelete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *laboofClient) BookmarkPurge(ctx context.Context, in *BookmarkPurgeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Laboof_BookmarkPurge_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LaboofServer is the server API for Laboof service.
// All implementations must embed UnimplementedLaboofServer
// for forward compatibility
type LaboofServer interface {
	TagCreate(context.Context, *TagCreateRequest) (*TagCreateResponse, error)
	TagList(context.Context, *TagListRequest) (*TagListResponse, error)
	TagGet(context.Context, *TagGetRequest) (*TagGetResponse, error)
	TagUpdate(context.Context, *TagUpdateRequest) (*TagUpdateResponse, error)
	TagDelete(context.Context, *TagDeleteRequest) (*TagDeleteResponse, error)
	TagPurge(context.Context, *TagPurgeRequest) (*emptypb.Empty, error)
	DomainCreate(context.Context, *DomainCreateRequest) (*DomainCreateResponse, error)
	DomainList(context.Context, *DomainListRequest) (*DomainListResponse, error)
	DomainGet(context.Context, *DomainGetRequest) (*DomainGetResponse, error)
	DomainUpdate(context.Context, *DomainUpdateRequest) (*DomainUpdateResponse, error)
	DomainDelete(context.Context, *DomainDeleteRequest) (*DomainDeleteResponse, error)
	DomainPurge(context.Context, *DomainPurgeRequest) (*emptypb.Empty, error)
	BookmarkCreate(context.Context, *BookmarkCreateRequest) (*BookmarkCreateResponse, error)
	BookmarkList(context.Context, *BookmarkListRequest) (*BookmarkListResponse, error)
	BookmarkGet(context.Context, *BookmarkGetRequest) (*BookmarkGetResponse, error)
	BookmarkUpdate(context.Context, *BookmarkUpdateRequest) (*BookmarkUpdateResponse, error)
	BookmarkDelete(context.Context, *BookmarkDeleteRequest) (*BookmarkDeleteResponse, error)
	BookmarkPurge(context.Context, *BookmarkPurgeRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedLaboofServer()
}

// UnimplementedLaboofServer must be embedded to have forward compatible implementations.
type UnimplementedLaboofServer struct {
}

func (UnimplementedLaboofServer) TagCreate(context.Context, *TagCreateRequest) (*TagCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TagCreate not implemented")
}
func (UnimplementedLaboofServer) TagList(context.Context, *TagListRequest) (*TagListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TagList not implemented")
}
func (UnimplementedLaboofServer) TagGet(context.Context, *TagGetRequest) (*TagGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TagGet not implemented")
}
func (UnimplementedLaboofServer) TagUpdate(context.Context, *TagUpdateRequest) (*TagUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TagUpdate not implemented")
}
func (UnimplementedLaboofServer) TagDelete(context.Context, *TagDeleteRequest) (*TagDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TagDelete not implemented")
}
func (UnimplementedLaboofServer) TagPurge(context.Context, *TagPurgeRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TagPurge not implemented")
}
func (UnimplementedLaboofServer) DomainCreate(context.Context, *DomainCreateRequest) (*DomainCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DomainCreate not implemented")
}
func (UnimplementedLaboofServer) DomainList(context.Context, *DomainListRequest) (*DomainListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DomainList not implemented")
}
func (UnimplementedLaboofServer) DomainGet(context.Context, *DomainGetRequest) (*DomainGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DomainGet not implemented")
}
func (UnimplementedLaboofServer) DomainUpdate(context.Context, *DomainUpdateRequest) (*DomainUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DomainUpdate not implemented")
}
func (UnimplementedLaboofServer) DomainDelete(context.Context, *DomainDeleteRequest) (*DomainDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DomainDelete not implemented")
}
func (UnimplementedLaboofServer) DomainPurge(context.Context, *DomainPurgeRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DomainPurge not implemented")
}
func (UnimplementedLaboofServer) BookmarkCreate(context.Context, *BookmarkCreateRequest) (*BookmarkCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BookmarkCreate not implemented")
}
func (UnimplementedLaboofServer) BookmarkList(context.Context, *BookmarkListRequest) (*BookmarkListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BookmarkList not implemented")
}
func (UnimplementedLaboofServer) BookmarkGet(context.Context, *BookmarkGetRequest) (*BookmarkGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BookmarkGet not implemented")
}
func (UnimplementedLaboofServer) BookmarkUpdate(context.Context, *BookmarkUpdateRequest) (*BookmarkUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BookmarkUpdate not implemented")
}
func (UnimplementedLaboofServer) BookmarkDelete(context.Context, *BookmarkDeleteRequest) (*BookmarkDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BookmarkDelete not implemented")
}
func (UnimplementedLaboofServer) BookmarkPurge(context.Context, *BookmarkPurgeRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BookmarkPurge not implemented")
}
func (UnimplementedLaboofServer) mustEmbedUnimplementedLaboofServer() {}

// UnsafeLaboofServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LaboofServer will
// result in compilation errors.
type UnsafeLaboofServer interface {
	mustEmbedUnimplementedLaboofServer()
}

func RegisterLaboofServer(s grpc.ServiceRegistrar, srv LaboofServer) {
	s.RegisterService(&Laboof_ServiceDesc, srv)
}

func _Laboof_TagCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TagCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaboofServer).TagCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Laboof_TagCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaboofServer).TagCreate(ctx, req.(*TagCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Laboof_TagList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TagListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaboofServer).TagList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Laboof_TagList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaboofServer).TagList(ctx, req.(*TagListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Laboof_TagGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TagGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaboofServer).TagGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Laboof_TagGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaboofServer).TagGet(ctx, req.(*TagGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Laboof_TagUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TagUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaboofServer).TagUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Laboof_TagUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaboofServer).TagUpdate(ctx, req.(*TagUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Laboof_TagDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TagDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaboofServer).TagDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Laboof_TagDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaboofServer).TagDelete(ctx, req.(*TagDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Laboof_TagPurge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TagPurgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaboofServer).TagPurge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Laboof_TagPurge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaboofServer).TagPurge(ctx, req.(*TagPurgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Laboof_DomainCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DomainCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaboofServer).DomainCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Laboof_DomainCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaboofServer).DomainCreate(ctx, req.(*DomainCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Laboof_DomainList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DomainListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaboofServer).DomainList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Laboof_DomainList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaboofServer).DomainList(ctx, req.(*DomainListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Laboof_DomainGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DomainGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaboofServer).DomainGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Laboof_DomainGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaboofServer).DomainGet(ctx, req.(*DomainGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Laboof_DomainUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DomainUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaboofServer).DomainUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Laboof_DomainUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaboofServer).DomainUpdate(ctx, req.(*DomainUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Laboof_DomainDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DomainDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaboofServer).DomainDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Laboof_DomainDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaboofServer).DomainDelete(ctx, req.(*DomainDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Laboof_DomainPurge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DomainPurgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaboofServer).DomainPurge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Laboof_DomainPurge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaboofServer).DomainPurge(ctx, req.(*DomainPurgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Laboof_BookmarkCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookmarkCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaboofServer).BookmarkCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Laboof_BookmarkCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaboofServer).BookmarkCreate(ctx, req.(*BookmarkCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Laboof_BookmarkList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookmarkListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaboofServer).BookmarkList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Laboof_BookmarkList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaboofServer).BookmarkList(ctx, req.(*BookmarkListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Laboof_BookmarkGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookmarkGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaboofServer).BookmarkGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Laboof_BookmarkGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaboofServer).BookmarkGet(ctx, req.(*BookmarkGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Laboof_BookmarkUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookmarkUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaboofServer).BookmarkUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Laboof_BookmarkUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaboofServer).BookmarkUpdate(ctx, req.(*BookmarkUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Laboof_BookmarkDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookmarkDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaboofServer).BookmarkDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Laboof_BookmarkDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaboofServer).BookmarkDelete(ctx, req.(*BookmarkDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Laboof_BookmarkPurge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookmarkPurgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaboofServer).BookmarkPurge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Laboof_BookmarkPurge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaboofServer).BookmarkPurge(ctx, req.(*BookmarkPurgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Laboof_ServiceDesc is the grpc.ServiceDesc for Laboof service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Laboof_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aufheben.v1.Laboof",
	HandlerType: (*LaboofServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TagCreate",
			Handler:    _Laboof_TagCreate_Handler,
		},
		{
			MethodName: "TagList",
			Handler:    _Laboof_TagList_Handler,
		},
		{
			MethodName: "TagGet",
			Handler:    _Laboof_TagGet_Handler,
		},
		{
			MethodName: "TagUpdate",
			Handler:    _Laboof_TagUpdate_Handler,
		},
		{
			MethodName: "TagDelete",
			Handler:    _Laboof_TagDelete_Handler,
		},
		{
			MethodName: "TagPurge",
			Handler:    _Laboof_TagPurge_Handler,
		},
		{
			MethodName: "DomainCreate",
			Handler:    _Laboof_DomainCreate_Handler,
		},
		{
			MethodName: "DomainList",
			Handler:    _Laboof_DomainList_Handler,
		},
		{
			MethodName: "DomainGet",
			Handler:    _Laboof_DomainGet_Handler,
		},
		{
			MethodName: "DomainUpdate",
			Handler:    _Laboof_DomainUpdate_Handler,
		},
		{
			MethodName: "DomainDelete",
			Handler:    _Laboof_DomainDelete_Handler,
		},
		{
			MethodName: "DomainPurge",
			Handler:    _Laboof_DomainPurge_Handler,
		},
		{
			MethodName: "BookmarkCreate",
			Handler:    _Laboof_BookmarkCreate_Handler,
		},
		{
			MethodName: "BookmarkList",
			Handler:    _Laboof_BookmarkList_Handler,
		},
		{
			MethodName: "BookmarkGet",
			Handler:    _Laboof_BookmarkGet_Handler,
		},
		{
			MethodName: "BookmarkUpdate",
			Handler:    _Laboof_BookmarkUpdate_Handler,
		},
		{
			MethodName: "BookmarkDelete",
			Handler:    _Laboof_BookmarkDelete_Handler,
		},
		{
			MethodName: "BookmarkPurge",
			Handler:    _Laboof_BookmarkPurge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aufheben/v1/aufheben.proto",
}
