export WASHAMBI_PG_DATABASE=washambi_local
export WASHAMBI_PG_HOST=localhost
export WASHAMBI_PG_USER=washambi_local
export WASHAMBI_PG_PASSWORD=washambi
export WASHAMBI_PG_PORT=5432

export WASHAMBI_URL=http://localhost

export WASHAMBI_CORNPOP_PORT=3010
export WASHAMBI_CORNPOP_URL=${WASHAMBI_URL}:${WASHAMBI_CORNPOP_PORT}

export WASHAMBI_FANCYPENOSI_PORT=3011
