#
# washambi
#
export WASHAMBI_PG_DATABASE=washambi_local
export WASHAMBI_PG_HOST=localhost
export WASHAMBI_PG_USER=washambi_local
export WASHAMBI_PG_PASSWORD=washambi
export WASHAMBI_PG_PORT=5432

export WASHAMBI_PROTOCOL=http://
export WASHAMBI_DOMAIN=localhost
export WASHAMBI_URL=${WASHAMBI_PROTOCOL}${WASHAMBI_DOMAIN}

#
# cornpop
#
export WASHAMBI_CORNPOP_PORT=3010
export WASHAMBI_CORNPOP_URL=${WASHAMBI_URL}:${WASHAMBI_CORNPOP_PORT}

#
# fancypenosi
#
export WASHAMBI_FANCYPENOSI_PORT=3011

#
# wokejak
#
export WASHAMBI_WOKEJAK_PORT=3012
