#
# washambi
#
export WASHAMBI_PG_DATABASE=washambi_local
export WASHAMBI_PG_HOST=127.0.0.1
export WASHAMBI_PG_USER=washambi_local
export WASHAMBI_PG_PASSWORD=washambi
export WASHAMBI_PG_PORT=5432

#
# blazerxd
#
export WASHAMBI_BLAZERXD_PORT=50051
export WASHAMBI_BLAZERXD_URL=127.0.0.1:${WASHAMBI_BLAZERXD_PORT}

#
# cornpop
#
export WASHAMBI_CORNPOP_PORT=3010
export WASHAMBI_CORNPOP_URL=http://127.0.0.1:${WASHAMBI_CORNPOP_PORT}

#
# fancypenosi
#
export WASHAMBI_FANCYPENOSI_PORT=3011
export WASHAMBI_FANCYPENOSI_URL=http://127.0.0.1:${WASHAMBI_FANCYPENOSI_PORT}

#
# wokejak
#
export WASHAMBI_WOKEJAK_PORT=3012
