//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	Bookmark = Bookmark.FromSchema(schema)
	BookmarkField = BookmarkField.FromSchema(schema)
	BookmarkFieldValue = BookmarkFieldValue.FromSchema(schema)
	BookmarksTags = BookmarksTags.FromSchema(schema)
	Domain = Domain.FromSchema(schema)
	DomainsTags = DomainsTags.FromSchema(schema)
	Profile = Profile.FromSchema(schema)
	ProfileField = ProfileField.FromSchema(schema)
	ProfileFieldValue = ProfileFieldValue.FromSchema(schema)
	Tag = Tag.FromSchema(schema)
}
