//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Bookmark struct {
	ID          uuid.UUID `sql:"primary_key"`
	UserID      uuid.UUID
	DomainID    uuid.UUID
	Description string
	URL         string
	CreatedAt   time.Time
	DeletedAt   *time.Time
}
